### ISSUE TITLE
Use GitHub actions to reload website

### ISSUE THREAD

**Issue by arBalasquide** [LukeSmithxyz/based.cooking#18]
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Based Cooking
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            git pull
            echo "Another Command"
```

In the actions tab you can allow github to ssh into your machine and run commands. In `Settings > Secrets > Repository Secrets` you can create the variables for `USERNAME`, `HOST`, `KEY`, etc.

The only thing you would have to change in the code block above is what comes after `git pull` with the commands needed for ssg5 to reload.
