### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by keeganjk** [LukeSmithxyz/based.cooking#212]
I think it would be a good idea to have a light mode, mainly for printing recipes. However, this may be considered "bloat" and will probably require Javascript, but I think that the ability to switch between/disable stylesheets without needing to edit the HTML may be helpful.

**Comment by keeganjk** [comment]
Also: I don't know how this would be applied site-wide since every page seems to be from an individual MD file, however, it should be possible since everything now uses the same stylesheet.

**Comment by 0jdxt** [comment]
If there were alternative styles for `body.light` then it could be toggled like:
```html
<button onclick="document.getElementsByTagName('body')[0].classList.toggle('light')">toggle theme</button>
```

**Comment by Goblin80** [comment]
The site already has a light color theme...

```css
@media(prefers - color - scheme: light) {
body {
    background: white;
    color: black;
}
a {
    color: blue;
}
a: visited {
    color: purple;
}
h2 {
    color: inherit;
}
code {
    color: forestgreen;
```

@keeganjk check your browser's preferred color scheme.
